import type { Metadata } from "next";
import AppFooter from "@/components/app/AppFooter";
import AppHeader from "@/components/app/AppHeader";
export const metadata: Metadata = {
  title: "Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppHeader />
        <main>
            {children}
        </main>
      <AppFooter />
      </body>
    </html>
  );
}
