import type { Metadata } from 'next'
import { Toaster } from '@/components/ui/toaster'
import './global.css'

export const metadata: Metadata = {
  title: 'Test',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        {children}
        <Toaster />
      </body>
    </html>
  )
}
